name = "FranklinTheorems"
uuid = "f9b7297b-b8b9-4883-a559-829bcd556a2f"
authors = ["RaphaelArkadyMeyerNYU <59720359+RaphaelArkadyMeyerNYU@users.noreply.github.com>"]
version = "0.1.1"

[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
FranklinUtils = "dcd8a645-c81d-482f-af4b-568f72f3e16d"

[compat]
FranklinUtils = "0.3.4"
Franklin = "0.10.29"
julia = "1.3"
